alacritty changed config file to toml - I'm kinda late though

diff --git a/.config/dmscripts/dm-font b/.config/dmscripts/dm-font
--- a/.config/dmscripts/dm-font
+++ b/.config/dmscripts/dm-font
@@ -8,7 +8,7 @@ read -r size xmobar_size <<< "${font_size[$choice]}"
 
 if [ "$choice" ]; then
     # Alacritty 
-    sed -i -e "s/family.*/family: ${choice}/g; s/size.*/size: ${size}/g" "$HOME"/.config/alacritty/alacritty.yml || echo "Error setting Alacritty Font"
+    sed -i -e "s/family=.*/family= \"${choice}\"/g; s/size=.*/size= ${size}/g" "$HOME"/.config/alacritty/alacritty.toml || echo "Error setting Alacritty Font"
     # Gtk font 
     sed -i "s/\/FontName.*/\/FontName \"$choice $size\"/g;" "$HOME"/.xsettingsd && killall -HUP xsettingsd || echo "Cannot modify xsettingsd"
     # XMOBAR
